### ISSUE TITLE
Using the Pandoc User Data Directory

### ISSUE THREAD

**Issue by iandol** [wlupton/pandoc-lua-logging#1] opened 2022-10-05 07:09 UTC
In your instructions, you suggest putting `logging.lua` in the same directory as the pandoc filters. In my case this is the standard path `~/.local/share/pandoc/filters/`. 
So I have:

```
▶︎ ll .local/share/pandoc/filters/logging*
-rw-r--r--@ 1 ian  staff   9.1K  5 Oct 12:26 .local/share/pandoc/filters/logging.lua
-rw-r--r--@ 1 ian  staff   588B  5 Oct 14:59 .local/share/pandoc/filters/loggingTest.lua
```

However if I call `local logging = require 'logging'` in `loggingTest.lua` then I get the following error:

```
pandoc -t html5 --verbose -L loggingTest.lua

---
title: My Title
---

Here.
[INFO] Running filter /Users/ian/.local/share/pandoc/filters/loggingTest.lua
Error running filter /Users/ian/.local/share/pandoc/filters/loggingTest.lua:
/Users/ian/.local/share/pandoc/filters/loggingTest.lua:2: module 'logging' not found:
	no field package.preload['logging']
	no file '/usr/local/share/lua/5.4/logging.lua'
	no file '/usr/local/share/lua/5.4/logging/init.lua'
	no file '/usr/local/lib/lua/5.4/logging.lua'
	no file '/usr/local/lib/lua/5.4/logging/init.lua'
	no file './logging.lua'
	no file './logging/init.lua'
	no file '/usr/local/lib/lua/5.4/logging.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './logging.so'
stack traceback:
	/Users/ian/.local/share/pandoc/filters/loggingTest.lua:2: in main chunk
```

I'm not a Lua person, but I understood that `./logging.lua` should have found it? My solution is the following:

```lua
local fpath = PANDOC_STATE.user_data_dir .. '/filters/'
local logging = dofile(fpath .. 'logging.lua')
```

But I'm sure I doing something stupid here!?

**Comment by wlupton** [comment] 2022-10-05 08:54
Ah, I think I've omitted a step. Sorry about that. `.local/share/pandoc/filters` will be searched by pandoc but here we're in the lua world, so the lua search path will need to be set. In fact I always run pandoc as follows, where `XXX` is the location of any required lua files (and indeed for me is also the location of the pandoc lua filters).

```
LUA_PATH="XXX/?.lua;;" pandoc
```

So you'll need something like this.

```
LUA_PATH="$HOME/.local/share/pandoc/filters/?.lua;;" pandoc
```

(You could also define the `LUA_PATH` environment variable statically.)

Does this work?

**Comment by iandol** [comment] 2022-10-05 10:29
OK, thanks, `LUA_PATH` should work for most of my workflows. In some cases pandoc is run by other tools (that may or may not respect `ENV`), and so in these cases using `PANDOC_STATE.user_data_dir` and `dofile` inside the lua file should work better I assume... Perhaps you can mention at least `LUA_PATH` in the readme? I'll close this and thanks for a very helpful script!

**Comment by wlupton** [comment] 2022-10-05 10:45
Thanks. Yes I'll definitely mention `LUA_PATH`. I'd be happy to mention alternatives such as `dofile` (which I haven't used) but perhaps it's more useful just to ensure that the issue is explained. I'll reopen this issue for now, and will close it when I've updated the docs (or created an issue to update the docs).

**Closed as completed** 2022-10-05 17:08 UTC
